core/app/[locale]/(default)/contentful/_components/sections/hero-banner.tsx, core/components/header/algolia-search.tsx, core/components/header/index.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/primitives/tabs/index.tsx, core/vibes/soul/sections/header-section/index.tsx
This fixes some issue with product nav / mobile nav states. It also updates the search UI to more closely match designs.
Test header and search on desktop and mobile.
=> Search and product nav UI

core/app/[locale]/(default)/contentful/_components/page-content-entries.tsx, core/app/[locale]/(default)/contentful/_components/sections/hero-carousel/index.tsx, core/app/[locale]/(default)/contentful/_components/sections/highlights.tsx, core/app/[locale]/(default)/contentful/_components/sections/product-bento/index.tsx, core/components/contentful/cta/index.tsx, core/contentful/schema.json, core/contentful/schema.ts, core/lib/utils.ts, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/sections/slideshow/index.tsx
Creates content types and components for shop pages
Go to /shop to see changes
=> Shop pages

core/vibes/soul/primitives/inline-email-form/index.tsx, core/vibes/soul/sections/footer/index.tsx
https://app.clickup.com/t/86b4d7r43
=> Lotus Footer

core/vibes/soul/primitives/navigation/index.tsx
https://app.clickup.com/t/86b4d7r1n
=> fix mobile language switcher

core/components/header/index.tsx, core/vibes/soul/primitives/banner/index.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/primitives/side-panel/index.tsx, core/vibes/soul/sections/header-section/index.tsx
https://app.clickup.com/t/86b4d7r1n
=> Mobile Header Styles

core/components/minicart/_actions/checkout.ts, core/components/minicart/index.tsx, core/vibes/soul/primitives/navigation/index.tsx
Action/loader for minicart checkout button, and place minicart over zendesk widget.
Open minicart and press checkout to see a loading state that takes you to a checkout screen. Also notice zendesk help widget is below the overlay on desktop and mobile
=> Minicart fixes

core/app/[locale]/(default)/contentful/contact/_actions/submit-form.ts, core/app/[locale]/(default)/contentful/contact/_components/chat-widget-button.tsx, core/app/[locale]/(default)/contentful/contact/_components/contact-form.tsx, core/app/[locale]/(default)/contentful/contact/page.tsx, core/components/cookie-preferences-notice/index.tsx, core/globals.css, core/types/window.d.ts, core/vibes/soul/form/field-error/index.tsx, core/vibes/soul/form/input/index.tsx, core/vibes/soul/form/label/index.tsx, core/vibes/soul/form/select/index.tsx, core/vibes/soul/primitives/modal/index.tsx
=> Zendesk Contact Form

core/app/[locale]/(default)/cart/page.tsx, core/messages/en.json, core/vibes/soul/form/radio-group/index.tsx, core/vibes/soul/sections/cart/client.tsx, core/vibes/soul/sections/cart/coupon-code-form/index.tsx, core/vibes/soul/sections/cart/helpful-links/index.tsx, core/vibes/soul/sections/cart/index.tsx, core/vibes/soul/sections/cart/shipping-form/index.tsx, core/vibes/soul/sections/sticky-sidebar-layout/index.tsx
https://app.clickup.com/t/86b4q6g10
=> Lotus Cart Styles

core/messages/en.json, core/vibes/soul/sections/cart/client.tsx, core/vibes/soul/sections/cart/coupon-code-form/index.tsx
https://app.clickup.com/t/86b4q6g10
=> Additional Cart Changes

core/app/[locale]/(default)/(auth)/register/_actions/register-customer.ts, core/components/contentful/sections/post-grid/index.tsx, core/components/contentful/sections/product-grid/index.tsx, core/components/header/algolia-search.tsx, core/components/header/index.tsx, core/vibes/soul/primitives/banner/index.tsx
Ensure Header Promo Banner content from Contentful is visible in the page header banner.
=> Header Promo Banner

core/app/[locale]/(default)/cart/_actions/add-to-cart-by-sku-form.ts, core/app/[locale]/(default)/cart/_actions/add-to-cart-by-sku.ts, core/client/queries/get-product-by-sku.ts, core/components/contentful/carousels/product-carousel/index.tsx, core/components/contentful/sections/product-bento/index.tsx, core/components/contentful/sections/product-grid/index.tsx, core/components/product-card/fragment.ts, core/data-transformers/product-card-transformer.ts, core/vibes/soul/primitives/product-card/index.tsx
Add to bag functionality for product cards and unified add-to-cart via sku action.
Hover over product cards throughout the website and click add to bag.
=> Interactive product card

core/components/contentful/sections/post-grid/index.tsx
This finalizes the post grid component algolia integration.
Go to /recipes and /features to test filtering, pagination, etc
=> Recipes / Features post grid algolia work

core/components/contentful/sections/post-grid/index.tsx
=> Clickable Post Card

core/app/[locale]/(default)/product/[slug]/page.tsx, core/components/notify-back-in-stock/_actions/subscribe.ts, core/components/notify-back-in-stock/_components/modal.tsx, core/components/notify-back-in-stock/index.tsx, core/components/notify-back-in-stock/schema.ts, core/lib/klaviyo.ts, core/vibes/soul/sections/product-detail/product-detail-form.tsx
=> Klaviyo Back in Stock Feature

core/vibes/soul/sections/account-settings/index.tsx, core/vibes/soul/sections/address-list-section/index.tsx, core/vibes/soul/sections/order-details-section/index.tsx, core/vibes/soul/sections/order-list/index.tsx
https://app.clickup.com/t/86b4q6gay
=> Fix Account Styles

core/app/[locale]/(default)/contentful/[...rest]/page.tsx, core/app/[locale]/(default)/contentful/faqs/page.tsx, core/app/[locale]/(default)/contentful/recipes/[...slug]/page.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/components/contentful/carousels/product-carousel/index.tsx, core/components/contentful/page-content-entries.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/inspiration-bento/index.tsx, core/components/contentful/sections/product-formulation-lookup-client.tsx, core/components/contentful/sections/product-formulation-lookup.tsx, core/components/contentful/sections/product-support-links.tsx, core/contentful/schema.json, core/contentful/schema.ts, core/data-transformers/product-card-transformer.ts, core/scripts/generate-contentful-schema.ts, core/vibes/soul/sections/product-detail/product-gallery.tsx, core/vibes/soul/sections/slideshow/index.tsx
Product formulation lookup page
Go to /product-formulation-lookup
=> Product Formulation Lookup

core/components/contentful/sections/post-grid/index.tsx, core/components/contentful/sections/product-grid/index.tsx, core/components/header/algolia-search.tsx, core/vibes/soul/primitives/product-card/index.tsx
Send click events for algolia results
Click on global search, or PLP, or features/recipes pages, then check analytics on Algolia.
=> Algolia click events

core/app/[locale]/(default)/account/wishlists/_components/new-wishlist-button.tsx, core/messages/en.json, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/sections/account-settings/index.tsx, core/vibes/soul/sections/order-list/index.tsx, core/vibes/soul/sections/sticky-sidebar-layout/index.tsx, core/vibes/soul/sections/wishlist-list-item/index.tsx, core/vibes/soul/sections/wishlists-section/index.tsx
https://app.clickup.com/t/86b4q6gay
=> Account Styles Fixes

core/app/[locale]/(default)/contentful/contact/_components/contact-form.tsx, core/app/[locale]/(default)/contentful/contact/form/page.tsx, core/app/[locale]/(default)/contentful/contact/page.tsx, core/components/wishlist/share-button.tsx, core/vibes/soul/sections/wishlist-details/index.tsx
https://app.clickup.com/t/86b4tba2c
=> Contact Page Form Styles

core/app/[locale]/(default)/product/[slug]/_components/share-button/index.tsx, core/app/[locale]/(default)/product/[slug]/_components/wishlist-button/index.tsx, core/app/[locale]/(default)/product/[slug]/page.tsx, core/vibes/soul/primitives/wishlist-item-card/index.tsx, core/vibes/soul/primitives/wishlist-item-card/wishlist-item-add-to-cart.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx
Adds share button and styles wishlist button on PDP. Also prevents duplicate add to bag in wishlist pages.
Go to a PDP and test sharing / wishlisting. Also go to /account/wishlists, detail, and public urls to see add to cart behavior.
=> Wish list polish

core/app/[locale]/(default)/contentful/faqs/_components/faq-sidebar.tsx, core/app/[locale]/(default)/contentful/faqs/page.tsx
https://app.clickup.com/t/86b4d7re9
=> FAQ Style Updates

core/app/[locale]/(default)/contentful/product-registration/_components/product-registration-form.tsx, core/app/[locale]/(default)/contentful/product-registration/page.tsx
=> Klaviyo Product Registration Edits

core/app/[locale]/(default)/contentful/recipes/[...slug]/page.tsx, core/components/contentful/sections/hero-banner.tsx, core/components/footer/index.tsx, core/contentful/schema.json, core/contentful/schema.ts, core/vibes/soul/sections/footer/index.tsx
=> Accessibility Review

core/app/[locale]/(default)/contentful/contact/_components/contact-form.tsx, core/app/[locale]/(default)/contentful/contact/form/page.tsx, core/app/[locale]/(default)/contentful/contact/page.tsx, core/app/[locale]/(default)/contentful/faqs/_components/faq-search.tsx, core/app/[locale]/(default)/contentful/faqs/_components/faq-sidebar.tsx, core/app/[locale]/(default)/contentful/faqs/page.tsx, core/app/[locale]/(default)/contentful/features/[...slug]/page.tsx, core/app/[locale]/(default)/contentful/policies/layout.tsx, core/app/[locale]/(default)/contentful/recipes/[...slug]/page.tsx, core/app/[locale]/(default)/contentful/tutorials/[...slug]/page.tsx, core/components/contentful/carousels/product-carousel/index.tsx, core/components/contentful/sections/community-section.tsx, core/components/contentful/sections/highlights.tsx, core/components/contentful/sections/inspiration-bento/index.tsx, core/components/contentful/sections/newsletter-form.tsx, core/components/contentful/sections/page-header.tsx, core/components/contentful/sections/product-grid/index.tsx, core/components/header/algolia-search.tsx, core/components/minicart/index.tsx, core/messages/en.json, core/middlewares/with-routes.ts, core/vibes/soul/primitives/banner/index.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/dynamic-form-section/index.tsx, core/vibes/soul/sections/footer/index.tsx, core/vibes/soul/sections/sign-in-section/index.tsx
=> Style Revisions

core/components/contentful/sections/hero-banner.tsx, core/components/contentful/sections/inspiration-bento/index.tsx, core/components/wistia-player.tsx, core/globals.css, core/vibes/soul/primitives/navigation/index.tsx
https://app.clickup.com/t/86b4vcrrr
=> Wistia Revisions

core/components/header/algolia-search.tsx, core/vibes/soul/primitives/navigation/index.tsx
=> Fix Global Search Close

core/components/minicart/index.tsx
=> Fix Minicart Subtotal Format

core/vibes/soul/primitives/banner/index.tsx
=> Update Accessibility Icon

core/components/contentful/sections/product-sticky-header.tsx, core/messages/en.json, core/vibes/soul/primitives/banner/index.tsx, core/vibes/soul/primitives/compare-card/index.tsx, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/primitives/wishlist-item-card/wishlist-item-add-to-cart.tsx, core/vibes/soul/sections/product-detail/product-detail-form.tsx
=> Update Add To Cart Copy

core/vibes/soul/sections/slideshow/index.tsx
=> Fix PDP Feature Background On Mobile

core/components/contentful/sections/card-section.tsx, core/lib/utils.ts
=> Fix Where To Buy URL

core/components/contentful/sections/faq-list.tsx, core/components/contentful/sections/hero-carousel/index.tsx
=> Fix FAQ Logic

core/components/contentful/sections/hero-section.tsx, core/contentful/schema.json, core/contentful/schema.ts
=> Hero Section Image Update

core/vibes/soul/primitives/banner/index.tsx
=> Update Banner Padding

core/components/contentful/page-content-entries.tsx, core/components/contentful/sections/media-banner.tsx, core/contentful/schema.json, core/contentful/schema.ts
https://app.clickup.com/t/86b51w44z
=> Add Media Banner

core/components/contentful/sections/card-section.tsx, core/components/contentful/sections/highlights.tsx, core/components/contentful/sections/product-bento/index.tsx, core/contentful/schema.json, core/contentful/schema.ts
https://app.clickup.com/t/86b51w5w6
=> Updates Inspiration Cards

core/components/contentful/carousels/alt-product-carousel/index.tsx
https://app.clickup.com/t/86b51w5w6
=> Fix Carousel Pagination

core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/(auth)/register/page.tsx, core/app/[locale]/(default)/contentful/contact/_components/contact-form.tsx, core/app/[locale]/(default)/contentful/product-registration/_actions/submit-form.ts, core/app/[locale]/(default)/contentful/product-registration/_components/product-registration-form.tsx, core/app/[locale]/(default)/contentful/product-registration/page.tsx, core/components/subscribe/_actions/subscribe.ts, core/lib/klaviyo.ts, core/messages/en.json, core/vibes/soul/sections/dynamic-form-section/index.tsx
=> Product Registration

.platform.app.yaml, core/components/contentful/feature-tile.tsx, core/components/contentful/page-content-entries.tsx, core/components/contentful/sections/block-product-features-accordion.tsx, core/components/contentful/sections/block-product-features.tsx, core/components/contentful/sections/product-sticky-header.tsx, core/components/wistia-player.tsx, core/contentful/schema.json, core/contentful/schema.ts, core/vibes/soul/sections/product-detail/index.tsx
https://app.clickup.com/t/86b51w65k
=> PDP Updates

core/components/contentful/sections/hero-carousel/index.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/highlights.tsx, core/contentful/schema.json, core/contentful/schema.ts
=> Professional series

core/app/[locale]/(default)/contentful/recipes/[...slug]/page.tsx
https://app.clickup.com/t/86b5223dy
=> Updates Recipe Page Styling

core/app/[locale]/(default)/contentful/tutorials/[...slug]/page.tsx, core/components/contentful/sections/block-product-features-accordion.tsx, core/components/contentful/sections/block-product-features.tsx, core/components/contentful/sections/hero-banner.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/inspiration-bento/index.tsx, core/components/contentful/sections/media-banner.tsx, core/components/contentful/sections/product-sticky-header.tsx, core/components/wistia-player.tsx, core/globals.css
https://app.clickup.com/t/86b52161c
=> Wistia Player Revisions

core/app/[locale]/(default)/contentful/features/[...slug]/page.tsx
https://app.clickup.com/t/86b521rv0
=> Fix Features Page Images

core/components/minicart/_actions/minicart.ts
https://app.clickup.com/t/86b526f0w
=> Fix minicart sales price

core/app/[locale]/(default)/contentful/faqs/_components/faq-sidebar.tsx, core/app/[locale]/(default)/contentful/faqs/page.tsx, core/components/contentful/sections/faq-list.tsx, core/contentful/schema.json, core/contentful/schema.ts
https://app.clickup.com/t/86b522c1e
=> FAQ Category Fix

core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/product-detail/product-gallery.tsx
https://app.clickup.com/t/86b51w65k
=> PDP Additional Image Tags

core/components/contentful/sections/hero-banner.tsx, core/components/contentful/sections/hero-carousel/index.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/highlights.tsx, core/components/contentful/sections/product-bento/index.tsx, core/contentful/schema.json, core/contentful/schema.ts, core/vibes/soul/primitives/product-card/index.tsx
=> Explore Professional Series Style Fixes

core/components/contentful/feature-tile.tsx
=> Fix PDP Feature Tile Icons

core/components/contentful/sections/block-product-features-accordion.tsx, core/components/contentful/sections/block-product-features.tsx, core/vibes/soul/sections/product-detail/index.tsx
=> PDP Style Fixes

core/globals.css, core/vibes/soul/form/input/index.tsx, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/sections/order-list/index.tsx
=> Updates Account Styles

core/app/[locale]/(default)/product/[slug]/page.tsx, core/components/contentful/sections/guiding-principles-section.tsx, core/contentful/schema.json, core/contentful/schema.ts
=> Our Story CTA Fix

core/components/contentful/sections/product-grid/index.tsx, core/vibes/soul/form/select-field/index.tsx, core/vibes/soul/primitives/select/index.tsx
=> Update Vibes Select

core/components/minicart/index.tsx, core/vibes/soul/form/number-input/index.tsx, core/vibes/soul/primitives/navigation/index.tsx
=> Minicart Style Updates

core/app/[locale]/(default)/search/_components/algolia-search.tsx, core/components/contentful/sections/card-section.tsx, core/components/contentful/sections/community-section.tsx, core/components/contentful/sections/guiding-principles-section.tsx, core/components/contentful/sections/hero-banner.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/highlights.tsx, core/components/contentful/sections/post-grid/index.tsx, core/components/contentful/sections/product-grid/index.tsx, core/components/contentful/sections/product-support-links.tsx, core/components/minicart/index.tsx, core/vibes/soul/sections/slideshow/index.tsx
=> Site Style Fixes

core/components/contentful/carousels/alt-product-carousel/index.tsx, core/components/contentful/sections/hero-banner.tsx, core/components/contentful/sections/hero-carousel/index.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/product-grid/index.tsx, core/globals.css, core/vibes/soul/lib/element-fade.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/sections/slideshow/index.tsx
https://app.clickup.com/t/86b51w3qz
=> Site Enhancements And Fixes

core/app/[locale]/(default)/contentful/recipes/[...slug]/page.tsx, core/app/[locale]/(default)/search/_components/algolia-search.tsx, core/components/contentful/carousels/product-carousel/index.tsx, core/components/contentful/sections/block-product-features.tsx, core/components/contentful/sections/card-section.tsx, core/components/contentful/sections/carousel-section.tsx, core/components/contentful/sections/community-section.tsx, core/components/contentful/sections/feature-item.tsx, core/components/contentful/sections/guiding-principles-section.tsx, core/components/contentful/sections/hero-banner.tsx, core/components/contentful/sections/hero-carousel/index.tsx, core/components/contentful/sections/hero-section.tsx, core/components/contentful/sections/highlights.tsx, core/components/contentful/sections/inspiration-bento/index.tsx, core/components/contentful/sections/newsletter-form.tsx, core/components/contentful/sections/post-grid/index.tsx, core/components/contentful/sections/product-bento/index.tsx, core/components/contentful/sections/product-sticky-header.tsx, core/components/wistia-player.tsx, core/vibes/soul/lib/element-fade.tsx, core/vibes/soul/primitives/carousel/index.tsx, core/vibes/soul/primitives/navigation/index.tsx, core/vibes/soul/primitives/price-label/index.tsx, core/vibes/soul/primitives/side-panel/index.tsx, core/vibes/soul/sections/product-detail/index.tsx, core/vibes/soul/sections/product-detail/product-gallery.tsx, core/vibes/soul/sections/section-layout/index.tsx, core/vibes/soul/sections/sidebar-menu/sidebar-menu-select.tsx, core/vibes/soul/sections/sign-in-section/index.tsx, core/vibes/soul/sections/slideshow/index.tsx
https://app.clickup.com/t/86b554uhe
=> Lotus UAT Batch #1

core/app/[locale]/(default)/(auth)/login/page.tsx, core/app/[locale]/(default)/cart/page.tsx, core/app/[locale]/(default)/contentful/[...rest]/page.tsx, core/app/[locale]/(default)/contentful/faqs/_components/faq-schema.tsx, core/app/[locale]/(default)/contentful/faqs/page.tsx, core/app/[locale]/(default)/contentful/product-registration/page.tsx, core/app/[locale]/(default)/search/page.tsx, core/components/contentful/sections/hero-carousel/index.tsx, core/components/contentful/sections/post-grid/index.tsx, core/components/contentful/sections/product-grid/index.tsx, core/components/contentful/sections/product-support-links.tsx, core/components/wistia-player.tsx, core/vibes/soul/primitives/product-card/index.tsx, core/vibes/soul/primitives/select/index.tsx, core/vibes/soul/sections/cart/shipping-form/index.tsx, core/vibes/soul/sections/slideshow/index.tsx
https://app.clickup.com/54655/v/l/li/901409323273?pr=90142444942
=> SEO UAT Batch #1

core/vibes/soul/sections/cart/index.tsx, core/vibes/soul/sections/order-list/index.tsx, core/vibes/soul/sections/wishlist-list-item/index.tsx
=> Updates Button Skeleton

core/components/contentful/sections/newsletter-form.tsx, core/components/cookie-preferences-cta/index.tsx, core/vibes/soul/sections/footer/index.tsx
https://app.clickup.com/t/86b585xuw
=> Update Cookie Preference CTA Styles
